### ISSUE TITLE
Exclude emails from check

### ISSUE THREAD

**Issue by noxify** [fuma-nama/next-validate-link#18]
Hi,

currently playing around to integrate `next-validate-link`.

I have created an example mdx which includes different kinds of urls.

I have tested it with

```
[email](email@example.com)
```

and

```
[email](mailto:email@example.com)
```

but got the email as finding while running the link check.

```
email@example.com: not-found at line 61 column 48
``` 

* is this the expected behaviour?
* Do you need something else?

**Comment by fuma-nama** [comment]
Yes it's likely a bug, fix coming soon

**Comment by noxify** [comment]
thanks for the quick fix - tested it quickly and everything seems to work with `1.4.0`
